### ISSUE TITLE
Populate new database with Android user data

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#77]
**Describe the solution you'd like**
If an old user is trying to use the new web app, we need to fetch data from the OTTAA Android database and store it on the new one and use it on the web app. Use a Cloudfunction to do so. 

Data to be retrieved first and fast.
- [x] Name
- [x] Date of birth
- [x] Gender
- [x] Pago

Other data
- [x] Pictos
- [x] Grupos
- [x] Frases

Test
- [x] Test that everything is working properly

**Comment by lopezjuanma96** [comment]
The Cloud Functions are basically done, we are getting the data on flutter but for now we aren't saving them on the database because we are defining it's new structure. It's done with two Cloud Functions, one on each Firebase Project, so that each project manages it's own data. When OTTAA Flutter signs in a new user a function is triggered to request that user's data to OTTAA Android which has another function that on the request searches for that user's data and returns it through HTTP

**Comment by lopezjuanma96** [comment]
Cloud functions are now writing to a test database with the structure proposed aboe¿ve, once this structure gets approved and implemented, it's only a matter of changing the database address from the test to the production one. (and maybe add some changes to names and such, that can come from approving this data)
